/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PublicVouch {
    rank: string;
    reviewText: string;
    timestamp: bigint;
    rating: bigint;
    anonymousUsername: string;
}
export interface PurchaseRecord {
    status: Variant_pending_confirmed_failed;
    paymentMethod: PaymentMethod;
    accountId: string;
    timestamp: bigint;
    buyerPrincipal: Principal;
    txHash: string;
    purchaseId: string;
}
export interface PublicListing {
    id: string;
    status: Status;
    rank: string;
    specialDeal: boolean;
    priceE8s: bigint;
}
export interface Vouch {
    vouchId: string;
    rank: string;
    hidden: boolean;
    reviewText: string;
    timestamp: bigint;
    buyerPrincipal: Principal;
    rating: bigint;
    purchaseId: string;
    anonymousUsername: string;
}
export interface UserProfile {
    name: string;
}
export enum PaymentMethod {
    btc = "btc",
    eth = "eth",
    icp = "icp"
}
export enum Status {
    sold = "sold",
    available = "available"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_notAuthenticated_notPurchased_alreadyVouched_success_invalidRating {
    notAuthenticated = "notAuthenticated",
    notPurchased = "notPurchased",
    alreadyVouched = "alreadyVouched",
    success = "success",
    invalidRating = "invalidRating"
}
export enum Variant_pending_confirmed_failed {
    pending = "pending",
    confirmed = "confirmed",
    failed = "failed"
}
export enum Variant_success_alreadyClaimed {
    success = "success",
    alreadyClaimed = "alreadyClaimed"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addListing(id: string, rank: string, priceE8s: bigint, specialDeal: boolean, encryptedCredentialRef: Uint8Array): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimAdmin(): Promise<Variant_success_alreadyClaimed>;
    deleteListing(id: string): Promise<void>;
    deleteVouch(vouchId: string): Promise<void>;
    filterByRank(rank: string): Promise<Array<PublicListing>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCredential(accountId: string, purchaseId: string): Promise<{
        __kind__: "viewLimitExceeded";
        viewLimitExceeded: null;
    } | {
        __kind__: "notAuthenticated";
        notAuthenticated: null;
    } | {
        __kind__: "notPurchased";
        notPurchased: null;
    } | {
        __kind__: "notFound";
        notFound: null;
    } | {
        __kind__: "success";
        success: Uint8Array;
    }>;
    getDecryptionKey(): Promise<Uint8Array | null>;
    getListingById(id: string): Promise<{
        __kind__: "notFound";
        notFound: null;
    } | {
        __kind__: "success";
        success: PublicListing;
    }>;
    getMyVouches(): Promise<Array<Vouch>>;
    getPublicVouches(): Promise<Array<PublicVouch>>;
    getPurchaseByBuyer(buyer: Principal): Promise<Array<PurchaseRecord>>;
    getSpecialDeals(): Promise<Array<PublicListing>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasPurchased(accountId: string): Promise<boolean>;
    hideVouch(vouchId: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listAllListings(): Promise<Array<PublicListing>>;
    markSold(id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setDecryptionKey(key: Uint8Array): Promise<void>;
    submitVouch(purchaseId: string, anonymousUsername: string, rank: string, rating: bigint, reviewText: string): Promise<Variant_notAuthenticated_notPurchased_alreadyVouched_success_invalidRating>;
    toggleSpecialDeal(id: string): Promise<void>;
    updateListingPrice(id: string, priceE8s: bigint): Promise<void>;
    uploadCredential(accountId: string, encryptedBlob: Uint8Array): Promise<void>;
    verifyBtcPayment(purchaseId: string, accountId: string, txHash: string): Promise<void>;
    verifyEthPayment(purchaseId: string, accountId: string, txHash: string): Promise<void>;
    verifyIcpPayment(purchaseId: string, accountId: string, _blockIndex: bigint): Promise<void>;
}
import type { PaymentMethod as _PaymentMethod, PublicListing as _PublicListing, PurchaseRecord as _PurchaseRecord, Status as _Status, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addListing(arg0: string, arg1: string, arg2: bigint, arg3: boolean, arg4: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addListing(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addListing(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimAdmin(): Promise<Variant_success_alreadyClaimed> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdmin();
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdmin();
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async deleteVouch(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVouch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVouch(arg0);
            return result;
        }
    }
    async filterByRank(arg0: string): Promise<Array<PublicListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByRank(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByRank(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCredential(arg0: string, arg1: string): Promise<{
        __kind__: "viewLimitExceeded";
        viewLimitExceeded: null;
    } | {
        __kind__: "notAuthenticated";
        notAuthenticated: null;
    } | {
        __kind__: "notPurchased";
        notPurchased: null;
    } | {
        __kind__: "notFound";
        notFound: null;
    } | {
        __kind__: "success";
        success: Uint8Array;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCredential(arg0, arg1);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCredential(arg0, arg1);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDecryptionKey(): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDecryptionKey();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDecryptionKey();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingById(arg0: string): Promise<{
        __kind__: "notFound";
        notFound: null;
    } | {
        __kind__: "success";
        success: PublicListing;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingById(arg0);
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingById(arg0);
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVouches(): Promise<Array<Vouch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVouches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVouches();
            return result;
        }
    }
    async getPublicVouches(): Promise<Array<PublicVouch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicVouches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicVouches();
            return result;
        }
    }
    async getPurchaseByBuyer(arg0: Principal): Promise<Array<PurchaseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseByBuyer(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseByBuyer(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpecialDeals(): Promise<Array<PublicListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpecialDeals();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpecialDeals();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasPurchased(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasPurchased(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasPurchased(arg0);
            return result;
        }
    }
    async hideVouch(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.hideVouch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hideVouch(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllListings(): Promise<Array<PublicListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllListings();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllListings();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async markSold(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSold(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSold(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setDecryptionKey(arg0: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDecryptionKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDecryptionKey(arg0);
            return result;
        }
    }
    async submitVouch(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<Variant_notAuthenticated_notPurchased_alreadyVouched_success_invalidRating> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVouch(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVouch(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleSpecialDeal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSpecialDeal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSpecialDeal(arg0);
            return result;
        }
    }
    async updateListingPrice(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListingPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListingPrice(arg0, arg1);
            return result;
        }
    }
    async uploadCredential(arg0: string, arg1: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadCredential(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadCredential(arg0, arg1);
            return result;
        }
    }
    async verifyBtcPayment(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyBtcPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyBtcPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async verifyEthPayment(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyEthPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyEthPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async verifyIcpPayment(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyIcpPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyIcpPayment(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_PaymentMethod_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PublicListing_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicListing): PublicListing {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseRecord_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseRecord): PurchaseRecord {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        confirmed: null;
    } | {
        failed: null;
    };
    paymentMethod: _PaymentMethod;
    accountId: string;
    timestamp: bigint;
    buyerPrincipal: Principal;
    txHash: string;
    purchaseId: string;
}): {
    status: Variant_pending_confirmed_failed;
    paymentMethod: PaymentMethod;
    accountId: string;
    timestamp: bigint;
    buyerPrincipal: Principal;
    txHash: string;
    purchaseId: string;
} {
    return {
        status: from_candid_variant_n18(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n19(_uploadFile, _downloadFile, value.paymentMethod),
        accountId: value.accountId,
        timestamp: value.timestamp,
        buyerPrincipal: value.buyerPrincipal,
        txHash: value.txHash,
        purchaseId: value.purchaseId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    rank: string;
    specialDeal: boolean;
    priceE8s: bigint;
}): {
    id: string;
    status: Status;
    rank: string;
    specialDeal: boolean;
    priceE8s: bigint;
} {
    return {
        id: value.id,
        status: from_candid_Status_n7(_uploadFile, _downloadFile, value.status),
        rank: value.rank,
        specialDeal: value.specialDeal,
        priceE8s: value.priceE8s
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    viewLimitExceeded: null;
} | {
    notAuthenticated: null;
} | {
    notPurchased: null;
} | {
    notFound: null;
} | {
    success: Uint8Array;
}): {
    __kind__: "viewLimitExceeded";
    viewLimitExceeded: null;
} | {
    __kind__: "notAuthenticated";
    notAuthenticated: null;
} | {
    __kind__: "notPurchased";
    notPurchased: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "success";
    success: Uint8Array;
} {
    return "viewLimitExceeded" in value ? {
        __kind__: "viewLimitExceeded",
        viewLimitExceeded: value.viewLimitExceeded
    } : "notAuthenticated" in value ? {
        __kind__: "notAuthenticated",
        notAuthenticated: value.notAuthenticated
    } : "notPurchased" in value ? {
        __kind__: "notPurchased",
        notPurchased: value.notPurchased
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notFound: null;
} | {
    success: _PublicListing;
}): {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "success";
    success: PublicListing;
} {
    return "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "success" in value ? {
        __kind__: "success",
        success: from_candid_PublicListing_n5(_uploadFile, _downloadFile, value.success)
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    confirmed: null;
} | {
    failed: null;
}): Variant_pending_confirmed_failed {
    return "pending" in value ? Variant_pending_confirmed_failed.pending : "confirmed" in value ? Variant_pending_confirmed_failed.confirmed : "failed" in value ? Variant_pending_confirmed_failed.failed : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    btc: null;
} | {
    eth: null;
} | {
    icp: null;
}): PaymentMethod {
    return "btc" in value ? PaymentMethod.btc : "eth" in value ? PaymentMethod.eth : "icp" in value ? PaymentMethod.icp : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notAuthenticated: null;
} | {
    notPurchased: null;
} | {
    alreadyVouched: null;
} | {
    success: null;
} | {
    invalidRating: null;
}): Variant_notAuthenticated_notPurchased_alreadyVouched_success_invalidRating {
    return "notAuthenticated" in value ? Variant_notAuthenticated_notPurchased_alreadyVouched_success_invalidRating.notAuthenticated : "notPurchased" in value ? Variant_notAuthenticated_notPurchased_alreadyVouched_success_invalidRating.notPurchased : "alreadyVouched" in value ? Variant_notAuthenticated_notPurchased_alreadyVouched_success_invalidRating.alreadyVouched : "success" in value ? Variant_notAuthenticated_notPurchased_alreadyVouched_success_invalidRating.success : "invalidRating" in value ? Variant_notAuthenticated_notPurchased_alreadyVouched_success_invalidRating.invalidRating : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: null;
} | {
    alreadyClaimed: null;
}): Variant_success_alreadyClaimed {
    return "success" in value ? Variant_success_alreadyClaimed.success : "alreadyClaimed" in value ? Variant_success_alreadyClaimed.alreadyClaimed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sold: null;
} | {
    available: null;
}): Status {
    return "sold" in value ? Status.sold : "available" in value ? Status.available : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PurchaseRecord>): Array<PurchaseRecord> {
    return value.map((x)=>from_candid_PurchaseRecord_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicListing>): Array<PublicListing> {
    return value.map((x)=>from_candid_PublicListing_n5(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
