/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PaymentMethod = { 'btc' : null } |
  { 'eth' : null } |
  { 'icp' : null };
export interface PublicListing {
  'id' : string,
  'status' : Status,
  'rank' : string,
  'specialDeal' : boolean,
  'priceE8s' : bigint,
}
export interface PublicVouch {
  'rank' : string,
  'reviewText' : string,
  'timestamp' : bigint,
  'rating' : bigint,
  'anonymousUsername' : string,
}
export interface PurchaseRecord {
  'status' : { 'pending' : null } |
    { 'confirmed' : null } |
    { 'failed' : null },
  'paymentMethod' : PaymentMethod,
  'accountId' : string,
  'timestamp' : bigint,
  'buyerPrincipal' : Principal,
  'txHash' : string,
  'purchaseId' : string,
}
export type Status = { 'sold' : null } |
  { 'available' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vouch {
  'vouchId' : string,
  'rank' : string,
  'hidden' : boolean,
  'reviewText' : string,
  'timestamp' : bigint,
  'buyerPrincipal' : Principal,
  'rating' : bigint,
  'purchaseId' : string,
  'anonymousUsername' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addListing' : ActorMethod<
    [string, string, bigint, boolean, Uint8Array],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdmin' : ActorMethod<
    [],
    { 'success' : null } |
      { 'alreadyClaimed' : null }
  >,
  'deleteListing' : ActorMethod<[string], undefined>,
  'deleteVouch' : ActorMethod<[string], undefined>,
  'filterByRank' : ActorMethod<[string], Array<PublicListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCredential' : ActorMethod<
    [string, string],
    { 'viewLimitExceeded' : null } |
      { 'notAuthenticated' : null } |
      { 'notPurchased' : null } |
      { 'notFound' : null } |
      { 'success' : Uint8Array }
  >,
  'getDecryptionKey' : ActorMethod<[], [] | [Uint8Array]>,
  'getListingById' : ActorMethod<
    [string],
    { 'notFound' : null } |
      { 'success' : PublicListing }
  >,
  'getMyVouches' : ActorMethod<[], Array<Vouch>>,
  'getPublicVouches' : ActorMethod<[], Array<PublicVouch>>,
  'getPurchaseByBuyer' : ActorMethod<[Principal], Array<PurchaseRecord>>,
  'getSpecialDeals' : ActorMethod<[], Array<PublicListing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasPurchased' : ActorMethod<[string], boolean>,
  'hideVouch' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllListings' : ActorMethod<[], Array<PublicListing>>,
  'markSold' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDecryptionKey' : ActorMethod<[Uint8Array], undefined>,
  'submitVouch' : ActorMethod<
    [string, string, string, bigint, string],
    { 'notAuthenticated' : null } |
      { 'notPurchased' : null } |
      { 'alreadyVouched' : null } |
      { 'success' : null } |
      { 'invalidRating' : null }
  >,
  'toggleSpecialDeal' : ActorMethod<[string], undefined>,
  'updateListingPrice' : ActorMethod<[string, bigint], undefined>,
  'uploadCredential' : ActorMethod<[string, Uint8Array], undefined>,
  'verifyBtcPayment' : ActorMethod<[string, string, string], undefined>,
  'verifyEthPayment' : ActorMethod<[string, string, string], undefined>,
  'verifyIcpPayment' : ActorMethod<[string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];