/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'sold' : IDL.Null,
  'available' : IDL.Null,
});
export const PublicListing = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'rank' : IDL.Text,
  'specialDeal' : IDL.Bool,
  'priceE8s' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Vouch = IDL.Record({
  'vouchId' : IDL.Text,
  'rank' : IDL.Text,
  'hidden' : IDL.Bool,
  'reviewText' : IDL.Text,
  'timestamp' : IDL.Int,
  'buyerPrincipal' : IDL.Principal,
  'rating' : IDL.Nat,
  'purchaseId' : IDL.Text,
  'anonymousUsername' : IDL.Text,
});
export const PublicVouch = IDL.Record({
  'rank' : IDL.Text,
  'reviewText' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
  'anonymousUsername' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'btc' : IDL.Null,
  'eth' : IDL.Null,
  'icp' : IDL.Null,
});
export const PurchaseRecord = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
    'failed' : IDL.Null,
  }),
  'paymentMethod' : PaymentMethod,
  'accountId' : IDL.Text,
  'timestamp' : IDL.Int,
  'buyerPrincipal' : IDL.Principal,
  'txHash' : IDL.Text,
  'purchaseId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Vec(IDL.Nat8)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimAdmin' : IDL.Func(
      [],
      [IDL.Variant({ 'success' : IDL.Null, 'alreadyClaimed' : IDL.Null })],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Text], [], []),
  'deleteVouch' : IDL.Func([IDL.Text], [], []),
  'filterByRank' : IDL.Func([IDL.Text], [IDL.Vec(PublicListing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCredential' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'viewLimitExceeded' : IDL.Null,
          'notAuthenticated' : IDL.Null,
          'notPurchased' : IDL.Null,
          'notFound' : IDL.Null,
          'success' : IDL.Vec(IDL.Nat8),
        }),
      ],
      [],
    ),
  'getDecryptionKey' : IDL.Func([], [IDL.Opt(IDL.Vec(IDL.Nat8))], []),
  'getListingById' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'notFound' : IDL.Null, 'success' : PublicListing })],
      ['query'],
    ),
  'getMyVouches' : IDL.Func([], [IDL.Vec(Vouch)], ['query']),
  'getPublicVouches' : IDL.Func([], [IDL.Vec(PublicVouch)], ['query']),
  'getPurchaseByBuyer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PurchaseRecord)],
      ['query'],
    ),
  'getSpecialDeals' : IDL.Func([], [IDL.Vec(PublicListing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasPurchased' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'hideVouch' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllListings' : IDL.Func([], [IDL.Vec(PublicListing)], ['query']),
  'markSold' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDecryptionKey' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'submitVouch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [
        IDL.Variant({
          'notAuthenticated' : IDL.Null,
          'notPurchased' : IDL.Null,
          'alreadyVouched' : IDL.Null,
          'success' : IDL.Null,
          'invalidRating' : IDL.Null,
        }),
      ],
      [],
    ),
  'toggleSpecialDeal' : IDL.Func([IDL.Text], [], []),
  'updateListingPrice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'uploadCredential' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
  'verifyBtcPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'verifyEthPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'verifyIcpPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({ 'sold' : IDL.Null, 'available' : IDL.Null });
  const PublicListing = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'rank' : IDL.Text,
    'specialDeal' : IDL.Bool,
    'priceE8s' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Vouch = IDL.Record({
    'vouchId' : IDL.Text,
    'rank' : IDL.Text,
    'hidden' : IDL.Bool,
    'reviewText' : IDL.Text,
    'timestamp' : IDL.Int,
    'buyerPrincipal' : IDL.Principal,
    'rating' : IDL.Nat,
    'purchaseId' : IDL.Text,
    'anonymousUsername' : IDL.Text,
  });
  const PublicVouch = IDL.Record({
    'rank' : IDL.Text,
    'reviewText' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
    'anonymousUsername' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'btc' : IDL.Null,
    'eth' : IDL.Null,
    'icp' : IDL.Null,
  });
  const PurchaseRecord = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'confirmed' : IDL.Null,
      'failed' : IDL.Null,
    }),
    'paymentMethod' : PaymentMethod,
    'accountId' : IDL.Text,
    'timestamp' : IDL.Int,
    'buyerPrincipal' : IDL.Principal,
    'txHash' : IDL.Text,
    'purchaseId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimAdmin' : IDL.Func(
        [],
        [IDL.Variant({ 'success' : IDL.Null, 'alreadyClaimed' : IDL.Null })],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Text], [], []),
    'deleteVouch' : IDL.Func([IDL.Text], [], []),
    'filterByRank' : IDL.Func([IDL.Text], [IDL.Vec(PublicListing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCredential' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'viewLimitExceeded' : IDL.Null,
            'notAuthenticated' : IDL.Null,
            'notPurchased' : IDL.Null,
            'notFound' : IDL.Null,
            'success' : IDL.Vec(IDL.Nat8),
          }),
        ],
        [],
      ),
    'getDecryptionKey' : IDL.Func([], [IDL.Opt(IDL.Vec(IDL.Nat8))], []),
    'getListingById' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'notFound' : IDL.Null, 'success' : PublicListing })],
        ['query'],
      ),
    'getMyVouches' : IDL.Func([], [IDL.Vec(Vouch)], ['query']),
    'getPublicVouches' : IDL.Func([], [IDL.Vec(PublicVouch)], ['query']),
    'getPurchaseByBuyer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PurchaseRecord)],
        ['query'],
      ),
    'getSpecialDeals' : IDL.Func([], [IDL.Vec(PublicListing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasPurchased' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'hideVouch' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllListings' : IDL.Func([], [IDL.Vec(PublicListing)], ['query']),
    'markSold' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDecryptionKey' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'submitVouch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [
          IDL.Variant({
            'notAuthenticated' : IDL.Null,
            'notPurchased' : IDL.Null,
            'alreadyVouched' : IDL.Null,
            'success' : IDL.Null,
            'invalidRating' : IDL.Null,
          }),
        ],
        [],
      ),
    'toggleSpecialDeal' : IDL.Func([IDL.Text], [], []),
    'updateListingPrice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'uploadCredential' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
    'verifyBtcPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'verifyEthPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'verifyIcpPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };